---
- name: Example Ansible Playbook for NGINX
  hosts: all
  become: true

  vars:
    nginx_listen_port: 8080

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - geerlingguy.nginx

