---
- name: Install and start Apache on Ubuntu
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache service
      systemd:
        name: apache2
        enabled: yes
        state: started

    - name: Create a custom index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
            <head><title>Harness + Ansible Demo</title></head>
            <body>
              <h1>Apache Installed via Ansible!</h1>
            </body>
          </html>
